### ISSUE TITLE
Plugins using System.Net.Sockets do not compile in version 1.27.0 and beyond (.NET 8 update)

### ISSUE THREAD

**Issue by f86k** [Yoooi0/MultiFunPlayer#181]
**Describe the issue**
There seems to be some issue with the .NET 8 implementation since plugins using System.Net.Sockets cannot compile (they work fine with 1.26.1 and earlier).

Error is:
`error CS1069: the type name 'TcpListener' could not be found in the namespace 'System.Net.Sockets'. This type has been forwarded to assembly...`

This is strange since I could not find any reference of TcpListener being removed in .NET 8.

![image](https://github.com/user-attachments/assets/e4abc860-76ef-4239-b20f-7024eed7d531)

**Expected behavior**
Plugins compile fine.

Plugin code:

```using MultiFunPlayer.Plugin;
using MultiFunPlayer.Common;
using System.Diagnostics;
using System.Globalization;
using System;
using System.IO;
using System.Text;
using System.Net.Sockets;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Linq;
using Stylet;
using System.Reflection;
using NLog;
using System.Xml.Serialization;

namespace Demo;

public class WebsocketPlugin : AsyncPluginBase
{
	private TcpListener _tcpListener = null;
	Socket client = null;

    protected override void Dispose(bool disposing)
    {
        if (_tcpListener != null)
        {
            _tcpListener.Stop();
        }
    }
    protected override async Task ExecuteAsync(CancellationToken cancellationToken)
    {
        _tcpListener = null;
		try
		{
			IPAddress ipAddress = IPAddress.Parse("127.0.0.1");

			Logger.Info("Starting TCP listener...");

			_tcpListener = new TcpListener(ipAddress, 5050);

			_tcpListener.Start();

			while (!cancellationToken.IsCancellationRequested)
			{
				
				Logger.Info("Server is listening on " + _tcpListener.LocalEndpoint);
				Logger.Debug("Waiting for a connection...");
				
				try
				{
					client = await _tcpListener.AcceptSocketAsync(cancellationToken);
				}
				catch (Exception)
				{
				   // continue;
				}

				if (client == null)
				{
					//continue;
				}

				Logger.Debug("Connection accepted.");
				
				byte[] data = new byte[1024];
				while (!cancellationToken.IsCancellationRequested)
				{
				   
					Logger.Debug("Reading data...");
					try
					{
						int size = client.Receive(data);
						string content = Encoding.UTF8.GetString(data).Substring(0, size);
						string[] ContArray = content.Split(",");
						double pos = double.Parse(ContArray[0]);
						double time = double.Parse(ContArray[1]);
						Logger.Debug($"Received data: {content}");
						InvokeAction("Axis::Value::Set", DeviceAxis.Parse("L0"), pos, time);         
					}
					catch (Exception e)
					{
						break;
						Logger.Debug(e, "or Client disconnected");
					}
				}
			}
		}
        catch (Exception e)
		{
				Logger.Error(e, "Error starting plugin");
		}
		finally
        {
			client.Close();
            Logger.Info("TcpListener closing");
			InvokeAction("Axis::Value::Set", DeviceAxis.Parse("L0"), 0.01, 0.5);
            if (_tcpListener != null)
            {
                _tcpListener.Stop();
            }
        }
    }
}```

**Comment by Yoooi0** [comment]
Hmm yea it seems like MFP code does not use `TcpListener` anywhere so the assembly is not referenced.
Add `//#r "name:System.Net.Sockets"` at the top and it should work.

I think you are also missing `using MultiFunPlayer.Plugin;`

**Comment by f86k** [comment]
> Hmm yea it seems like MFP code does not use `TcpListener` anywhere so the assembly is not referenced. Add `//#r "name:System.Net.Sockets"` at the top and it should work.
> 
> I think you are also missing `using MultiFunPlayer.Plugin;`

Adding `//#r "name:System.Net.Sockets"` worked, thanks! I'm curious about the double slash, usually that just makes the line a comment. Is the `//#r` specific to MFP plugins? Official C# syntax seems to be `#r` only: https://github.com/dotnet/interactive/blob/main/docs/magic-commands.md#c-kernel

**Comment by Yoooi0** [comment]
Last I checked if you try to compile the plugin with `#r` it wont work and will show a compilation error. It only seems to work in C# scripts, it does not work when compiling into a in memory dll/assembly.
I had to implement a similar feature for MFP plugins but it has to compile hence its commented. I think I tried to preprocess the source code so that `#r` would be commented for compilation inside MFP but then debugging does not work since the source code is different.

FYI you should be able to debug your plugin via Visual Studio or VSCode by attaching to MFP process and adding a breakpoint into your plugin source code.
